/////////////////////////////////////////////////////////////////////////////
// Name:        AlbumSplitterWiindow.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Wed 19 Jan 2022 14:01:07 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Wed 19 Jan 2022 14:01:07 CST

#ifndef _ALBUMSPLITTERWIINDOW_H_
#define _ALBUMSPLITTERWIINDOW_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/splitter.h"
#include "wx/treectrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxSplitterWindow;
class wxTreeCtrl;
class wxWindow;
////@end forward declarations
class DesignTreeCtrl;
class AlbumPanel;
class AlbumImagePanel;
/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ALBUMSPLITTERWINDOW 10000
#define ID_SECONDARYSPLITTERWINDOW 13005
#define ID_SCROLLEDWINDOW 10003
#define ID_AECMDTREECTRL 10001
#define ID_PANEL 10002
#define ID_CDDATATEXTCTRL 10005
#define ID_ALBUMALBUMIMAGEPANEL 10004
#define ID_ALBUMZOOMSLIDER 10006
#define SYMBOL_ALBUMSPLITTERWINDOW_STYLE wxTAB_TRAVERSAL
#define SYMBOL_ALBUMSPLITTERWINDOW_TITLE _("AlbumSplitterWindow")
#define SYMBOL_ALBUMSPLITTERWINDOW_IDNAME ID_ALBUMSPLITTERWINDOW
#define SYMBOL_ALBUMSPLITTERWINDOW_SIZE wxSize(400, 300)
#define SYMBOL_ALBUMSPLITTERWINDOW_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * AlbumSplitterWindow class declaration
 */

class AlbumSplitterWindow: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( AlbumSplitterWindow )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    AlbumSplitterWindow();
    AlbumSplitterWindow( wxWindow* parent, wxWindowID id = SYMBOL_ALBUMSPLITTERWINDOW_IDNAME, const wxPoint& pos = SYMBOL_ALBUMSPLITTERWINDOW_POSITION, const wxSize& size = SYMBOL_ALBUMSPLITTERWINDOW_SIZE, long style = SYMBOL_ALBUMSPLITTERWINDOW_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ALBUMSPLITTERWINDOW_IDNAME, const wxPoint& pos = SYMBOL_ALBUMSPLITTERWINDOW_POSITION, const wxSize& size = SYMBOL_ALBUMSPLITTERWINDOW_SIZE, long style = SYMBOL_ALBUMSPLITTERWINDOW_STYLE );

    /// Destructor
    ~AlbumSplitterWindow();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin AlbumSplitterWindow event handler declarations

////@end AlbumSplitterWindow event handler declarations

////@begin AlbumSplitterWindow member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end AlbumSplitterWindow member function declarations

    AlbumPanel* GetAlbumPanel(){ return m_albumPanel;} ;
    void OnZoomsliderUpdated( wxCommandEvent& event );

    /// Should we show tooltips?
    static bool ShowToolTips();
    void SetSashPosition( int pos ){ m_secondarySplitterWindow->SetSashPosition( pos ); };
////@begin AlbumSplitterWindow member variables
    wxSplitterWindow* m_secondarySplitterWindow;
    AlbumImagePanel* m_albumImagePanel;
////@end AlbumSplitterWindow member variables
    wxSlider* m_zoomSlider; ///< Pointer to image soom slider
    AlbumPanel* m_albumPanel ;
};

#endif
    // _ALBUMSPLITTERWIINDOW_H_
