/////////////////////////////////////////////////////////////////////////////
// Name:        AlbumDetailsDialog.cpp
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Wed 23 Nov 2022 12:01:34 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Wed 23 Nov 2022 12:01:34 CST

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
#include "wx/imaglist.h"
////@end includes

#include "AlbumDetailsDialog.h"

////@begin XPM images

////@end XPM images


/*
 * AlbumDetailsDialog type definition
 */

IMPLEMENT_DYNAMIC_CLASS( AlbumDetailsDialog, wxDialog )


/*
 * AlbumDetailsDialog event table definition
 */

BEGIN_EVENT_TABLE( AlbumDetailsDialog, wxDialog )

////@begin AlbumDetailsDialog event table entries
////@end AlbumDetailsDialog event table entries

END_EVENT_TABLE()


/*
 * AlbumDetailsDialog constructors
 */

AlbumDetailsDialog::AlbumDetailsDialog()
{
    Init();
}

AlbumDetailsDialog::AlbumDetailsDialog( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}


/*
 * AlbumDetailsDialog creator
 */

bool AlbumDetailsDialog::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin AlbumDetailsDialog creation
    SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY|wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end AlbumDetailsDialog creation
    return true;
}


/*
 * AlbumDetailsDialog destructor
 */

AlbumDetailsDialog::~AlbumDetailsDialog()
{
////@begin AlbumDetailsDialog destruction
////@end AlbumDetailsDialog destruction
}


/*
 * Member initialisation
 */

void AlbumDetailsDialog::Init()
{
////@begin AlbumDetailsDialog member initialisation
    m_name = NULL;
    m_height = NULL;
    m_width = NULL;
    m_topMargin = NULL;
    m_bottomMargin = NULL;
    m_rightMargin = NULL;
    m_leftMargin = NULL;
    m_borderSize = NULL;
    m_validate = NULL;
    m_statusList = NULL;
////@end AlbumDetailsDialog member initialisation
}


/*
 * Control creation for AlbumDetailsDialog
 */

void AlbumDetailsDialog::CreateControls()
{    
////@begin AlbumDetailsDialog content construction
    // Generated by DialogBlocks, Wed 23 Nov 2022 12:01:34 CST (unregistered)

    AlbumDetailsDialog* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer1 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer1);

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer1->Add(itemBoxSizer2, 0, wxGROW|wxALL, 0);

    m_name = new LabeledTextBox( itemDialog1, ID_NAMELABELEDTEXTBOX, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );
    m_name->SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    itemBoxSizer2->Add(m_name, 1, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer1->Add(itemBoxSizer4, 0, wxGROW|wxALL, 0);

    m_height = new LabeledTextBox( itemDialog1, ID_HEIGHTLABELEDTEXTBOX, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );
    m_height->SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    itemBoxSizer4->Add(m_height, 1, wxGROW|wxALL, 5);

    m_width = new LabeledTextBox( itemDialog1, ID_WIDTHLABELEDTEXTBOX, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );
    m_width->SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    itemBoxSizer4->Add(m_width, 1, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer7 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer1->Add(itemBoxSizer7, 0, wxGROW|wxALL, 0);

    m_topMargin = new LabeledTextBox( itemDialog1, ID_TOPMARGINLABELEDTEXTBOX, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );
    m_topMargin->SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    itemBoxSizer7->Add(m_topMargin, 1, wxGROW|wxALL, 5);

    m_bottomMargin = new LabeledTextBox( itemDialog1, ID_BOTTOMMARGINLABELEDTEXTBOX, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );
    m_bottomMargin->SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    itemBoxSizer7->Add(m_bottomMargin, 1, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer10 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer1->Add(itemBoxSizer10, 0, wxGROW|wxALL, 0);

    m_rightMargin = new LabeledTextBox( itemDialog1, ID_RIGHTMARGINLABELEDTEXTBOX, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );
    m_rightMargin->SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    itemBoxSizer10->Add(m_rightMargin, 1, wxGROW|wxALL, 5);

    m_leftMargin = new LabeledTextBox( itemDialog1, ID_LEFTMARGINLABELEDTEXTBOX, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );
    m_leftMargin->SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    itemBoxSizer10->Add(m_leftMargin, 1, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer1->Add(itemBoxSizer3, 0, wxGROW|wxALL, 0);

    m_borderSize = new LabeledTextBox( itemDialog1, ID_BORDERSIZELABELEDTEXTBOX, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );
    m_borderSize->SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    itemBoxSizer3->Add(m_borderSize, 1, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer13 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer1->Add(itemBoxSizer13, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 0);

    wxButton* itemButton14 = new wxButton( itemDialog1, ID_REFRESHBUTTON, _("Refresh from Catalog"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer13->Add(itemButton14, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    itemBoxSizer13->Add(5, 5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    m_validate = new wxButton( itemDialog1, ID_VALIDATEBUTTON, _("Validate"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer13->Add(m_validate, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxBoxSizer* itemBoxSizer17 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer1->Add(itemBoxSizer17, 2, wxGROW|wxALL, 5);

    m_statusList = new wxListCtrl( itemDialog1, ID_LISTCTRL, wxDefaultPosition, wxSize(100, 100), wxLC_REPORT|wxLC_NO_HEADER );
    itemBoxSizer17->Add(m_statusList, 2, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer19 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer1->Add(itemBoxSizer19, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 0);

    wxButton* itemButton20 = new wxButton( itemDialog1, wxID_CANCEL, _("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer19->Add(itemButton20, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton21 = new wxButton( itemDialog1, wxID_OK, _("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer19->Add(itemButton21, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

////@end AlbumDetailsDialog content construction
}


/*
 * Should we show tooltips?
 */

bool AlbumDetailsDialog::ShowToolTips()
{
    return true;
}

/*
 * Get bitmap resources
 */

wxBitmap AlbumDetailsDialog::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin AlbumDetailsDialog bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end AlbumDetailsDialog bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon AlbumDetailsDialog::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin AlbumDetailsDialog icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end AlbumDetailsDialog icon retrieval
}
