/////////////////////////////////////////////////////////////////////////////
// Name:        CatalogPanel.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Sat 22 Jan 2022 13:01:18 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Sat 22 Jan 2022 13:01:18 CST

#ifndef _CATALOGDATAPANEL_H_
#define _CATALOGDATAPANEL_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/treectrl.h"
////@end includes

#include "Defs.h"
#include "gui/GuiDefs.h"

#include "utils/Project.h"
#include "CatalogData.h"
/*!
 * Forward declarations
 */

////@begin forward declarations
class CatalogTreeCtrl;
////@end forward declarations

class Stamp;

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CATALOGDATAPANEL 10000
#define ID_TEXTCTRL 10007
#define ID_TREECTRL 10010
#define SYMBOL_CATALOGDATAPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_CATALOGDATAPANEL_TITLE _("CatalogPanel")
#define SYMBOL_CATALOGDATAPANEL_IDNAME ID_CATALOGDATAPANEL
#define SYMBOL_CATALOGDATAPANEL_SIZE wxSize(400, 300)
#define SYMBOL_CATALOGDATAPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * CatalogPanel class declaration
 */

class CatalogPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( CatalogPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CatalogPanel();
    CatalogPanel( wxWindow* parent, 
    wxWindowID id = SYMBOL_CATALOGDATAPANEL_IDNAME, 
    const wxPoint& pos = SYMBOL_CATALOGDATAPANEL_POSITION, 
    const wxSize& size = SYMBOL_CATALOGDATAPANEL_SIZE, 
    long style = SYMBOL_CATALOGDATAPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CATALOGDATAPANEL_IDNAME, const wxPoint& pos = SYMBOL_CATALOGDATAPANEL_POSITION, const wxSize& size = SYMBOL_CATALOGDATAPANEL_SIZE, long style = SYMBOL_CATALOGDATAPANEL_STYLE );

    /// Destructor
    ~CatalogPanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CatalogPanel event handler declarations

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL
    void OnTextctrlTextUpdated( wxCommandEvent& event );

////@end CatalogPanel event handler declarations

////@begin CatalogPanel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CatalogPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

    void SetStamp( Stamp* stamp );
    
    void UpdateStatus( );

    void LoadCatalogTree( );

    void ClearCatalogTree( );

    void LoadCatalog( );
    void InitCatalogData();
    void LoadCatalogCSV( wxString csvFilename );
    CatalogTreeCtrl* GetCatalogDataTree( ) { return m_listTree; };

 
 

////@begin CatalogPanel member variables
    wxTextCtrl* m_title;
    CatalogTreeCtrl* m_listTree;
////@end CatalogPanel member variables
  
    wxTreeItemId m_draggedItem;
    
    Stamp* m_stamp;
    
    wxTreeItemId m_currentItem;

};

#endif
    // _CATALOGDATAPANEL_H_
