/////////////////////////////////////////////////////////////////////////////
// Name:        ColDetailsDialog.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Fri 29 Apr 2022 17:39:37 CDT
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Fri 29 Apr 2022 17:39:37 CDT

#ifndef _COLDETAILSDIALOG_H_
#define _COLDETAILSDIALOG_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/listctrl.h"
////@end includes

#include "gui/DesignTreeCtrl.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
class LabeledTextBox;
class wxListCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_COLDETAILSDIALOG 10000
#define ID_NAMELABELEDTEXTBOX 10009
#define ID_COLTITLECHECKBOX 10004
#define ID_FRAMECHECKBOX 10006
#define ID_LISTCTRL 10006
#define SYMBOL_COLDETAILSDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_COLDETAILSDIALOG_TITLE _("Col Details Dialog")
#define SYMBOL_COLDETAILSDIALOG_IDNAME ID_COLDETAILSDIALOG
#define SYMBOL_COLDETAILSDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_COLDETAILSDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ColDetailsDialog class declaration
 */

class ColDetailsDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( ColDetailsDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ColDetailsDialog();
    ColDetailsDialog( wxWindow* parent, wxWindowID id = SYMBOL_COLDETAILSDIALOG_IDNAME, const wxString& caption = SYMBOL_COLDETAILSDIALOG_TITLE, const wxPoint& pos = SYMBOL_COLDETAILSDIALOG_POSITION, const wxSize& size = SYMBOL_COLDETAILSDIALOG_SIZE, long style = SYMBOL_COLDETAILSDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_COLDETAILSDIALOG_IDNAME, const wxString& caption = SYMBOL_COLDETAILSDIALOG_TITLE, const wxPoint& pos = SYMBOL_COLDETAILSDIALOG_POSITION, const wxSize& size = SYMBOL_COLDETAILSDIALOG_SIZE, long style = SYMBOL_COLDETAILSDIALOG_STYLE );

    /// Destructor
    ~ColDetailsDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin ColDetailsDialog event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_OK
    void OnOkClick( wxCommandEvent& event );

////@end ColDetailsDialog event handler declarations

////@begin ColDetailsDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ColDetailsDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();
    void SetNameModified( bool state ) ;
    void SetDesignTreeID(wxTreeItemId id );
    bool IsNameModified( ) ;
    wxTreeItemId m_designTreeID;
////@begin ColDetailsDialog member variables
    LabeledTextBox* m_name;
    wxCheckBox* m_titleCheckbox;
    wxCheckBox* m_frameCheckbox;
    wxListCtrl* m_statusList;

////@end ColDetailsDialog member variables
};

#endif
    // _COLDETAILSDIALOG_H_
