/////////////////////////////////////////////////////////////////////////////
// Name:        ComparePanel.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     Fri 12 Jan 2024 09:54:20 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Fri 12 Jan 2024 09:54:20 CST

#ifndef _COMPAREPANEL_H_
#define _COMPAREPANEL_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_COMPAREPANEL 10000
#define ID_TARGETFILE 10001
#define ID_MERGEFILE 10002
#define ID_NEXTENTRY 10003
#define ID_PREVENTRY 10004
#define ID_SHOWDIFFSONLY 10005
#define ID_SHOWALL 10006
#define ID_COPYALL 10009
#define ID_UNDOCOPYALL 10008
#define ID_SCROLLEDWINDOW 10010
#define ID_TEXTCTRL5 10015
#define ID_BITMAPBUTTON9 10017
#define ID_BITMAPBUTTON3 10007
#define ID_TEXTCTRL6 10016
#define ID_TEXTCTRL2 10011
#define ID_BITMAPBUTTON5 10012
#define ID_BITMAPBUTTON6 10013
#define ID_TEXTCTRL3 10014
#define ID_TEXTCTRL4 10018
#define ID_BITMAPBUTTON7 10019
#define ID_BITMAPBUTTON8 10020
#define ID_TEXTCTRL7 10021
#define SYMBOL_COMPAREPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_COMPAREPANEL_TITLE _("ComparePanel")
#define SYMBOL_COMPAREPANEL_IDNAME ID_COMPAREPANEL
#define SYMBOL_COMPAREPANEL_SIZE wxSize(600, 300)
#define SYMBOL_COMPAREPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ComparePanel class declaration
 */

class ComparePanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( ComparePanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ComparePanel();
    ComparePanel( wxWindow* parent, wxWindowID id = SYMBOL_COMPAREPANEL_IDNAME, const wxPoint& pos = SYMBOL_COMPAREPANEL_POSITION, const wxSize& size = SYMBOL_COMPAREPANEL_SIZE, long style = SYMBOL_COMPAREPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_COMPAREPANEL_IDNAME, const wxPoint& pos = SYMBOL_COMPAREPANEL_POSITION, const wxSize& size = SYMBOL_COMPAREPANEL_SIZE, long style = SYMBOL_COMPAREPANEL_STYLE );

    /// Destructor
    ~ComparePanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin ComparePanel event handler declarations

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TARGETFILE
    void OnTargetfileTextUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_MERGEFILE
    void OnMergefileTextUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_NEXTENTRY
    void OnNextentryClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_PREVENTRY
    void OnPreventryClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_RADIOBUTTON_SELECTED event handler for ID_SHOWDIFFSONLY
    void OnShowdiffsonlySelected( wxCommandEvent& event );

    /// wxEVT_COMMAND_RADIOBUTTON_SELECTED event handler for ID_SHOWALL
    void OnShowallSelected( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_COPYALL
    void OnCopyallClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_UNDOCOPYALL
    void OnUndocopyallClick( wxCommandEvent& event );

////@end ComparePanel event handler declarations

////@begin ComparePanel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ComparePanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ComparePanel member variables
    wxTextCtrl* m_targetFile;
    wxStaticText* m_typeName;
    wxStaticText* m_typeName;
    wxTextCtrl* m_targetVal;
    wxBitmapButton* m_merge;
    wxBitmapButton* m_undo;
    wxTextCtrl* m_mergeVal;
    wxStaticText* m_typeName;
    wxTextCtrl* m_targetVal;
    wxBitmapButton* m_merge;
    wxBitmapButton* m_undo;
    wxTextCtrl* m_mergeVal;
    wxStaticText* m_typeName;
    wxTextCtrl* m_targetVal;
    wxBitmapButton* m_merge;
    wxBitmapButton* m_undo;
    wxTextCtrl* m_mergeVal;
////@end ComparePanel member variables
};

#endif
    // _COMPAREPANEL_H_
