/////////////////////////////////////////////////////////////////////////////
// Name:        FileCreateDialog.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Fri 20 Jan 2023 19:33:48 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Fri 20 Jan 2023 19:33:48 CST

#ifndef _FILECREATEDIALOG_H_
#define _FILECREATEDIALOG_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_FILECREATEDIALOG 10000
#define ID_TEXTCTRL2 10001
#define SYMBOL_FILECREATEDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_FILECREATEDIALOG_TITLE _("Select file and directory")
#define SYMBOL_FILECREATEDIALOG_IDNAME ID_FILECREATEDIALOG
#define SYMBOL_FILECREATEDIALOG_SIZE wxSize(600, 300)
#define SYMBOL_FILECREATEDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * FileCreateDialog class declaration
 */

class FileCreateDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( FileCreateDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    FileCreateDialog();
    FileCreateDialog( wxWindow* parent, wxWindowID id = SYMBOL_FILECREATEDIALOG_IDNAME, const wxString& caption = SYMBOL_FILECREATEDIALOG_TITLE, const wxPoint& pos = SYMBOL_FILECREATEDIALOG_POSITION, const wxSize& size = SYMBOL_FILECREATEDIALOG_SIZE, long style = SYMBOL_FILECREATEDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_FILECREATEDIALOG_IDNAME, const wxString& caption = SYMBOL_FILECREATEDIALOG_TITLE, const wxPoint& pos = SYMBOL_FILECREATEDIALOG_POSITION, const wxSize& size = SYMBOL_FILECREATEDIALOG_SIZE, long style = SYMBOL_FILECREATEDIALOG_STYLE );

    /// Destructor
    ~FileCreateDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin FileCreateDialog event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_CANCEL
    void OnCancelClick( wxCommandEvent& event );
    void OnOKClick( wxCommandEvent& event );

////@end FileCreateDialog event handler declarations

////@begin FileCreateDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end FileCreateDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();
    wxString GetPath( );
    wxString GetFile( );
    wxString GetDir( );
    void SetDefaultDirectory( wxString str) { m_defaultDirectory = str; m_fileCtrl->SetDirectory(str);};
    void SetDefaultFilename( wxString str) { m_defaultFilename = str; m_fileCtrl->SetFilename(str);}; 
    void SetWildCard( wxString str) { m_wildCard = str; m_fileCtrl->SetWildcard(str);};

////@begin FileCreateDialog member variables
////@end FileCreateDialog member variables
    wxString m_path ;
    wxString m_file ;
    wxString m_dir ;
    wxString m_defaultDirectory; 
    wxString m_defaultFilename; 
    wxString m_wildCard;
    wxFileCtrl* m_fileCtrl;
};

#endif
    // _FILECREATEDIALOG_H_
