/////////////////////////////////////////////////////////////////////////////
// Name:        gui/GalleryImagePanel.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Mon 21 Feb 2022 17:10:36 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Mon 21 Feb 2022 17:10:36 CST

#ifndef _GALLERYALBUMIMAGEPANEL_H_
#define _GALLERYALBUMIMAGEPANEL_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_GALLERYALBUMIMAGEPANEL 10000
#define wxID_BITMAPSTATIC 10026
#define wxID_IDSTATIC 10025
#define wxID_TITLESTATIC 10024
#define SYMBOL_GALLERYALBUMIMAGEPANEL_STYLE wxNO_BORDER|wxTAB_TRAVERSAL
#define SYMBOL_GALLERYALBUMIMAGEPANEL_TITLE _("GalleryImagePanel")
#define SYMBOL_GALLERYALBUMIMAGEPANEL_IDNAME ID_GALLERYALBUMIMAGEPANEL
#define SYMBOL_GALLERYALBUMIMAGEPANEL_SIZE wxSize(70, 70)
#define SYMBOL_GALLERYALBUMIMAGEPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * GalleryImagePanel class declaration
 */

class GalleryImagePanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( GalleryImagePanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    GalleryImagePanel();
    GalleryImagePanel( wxWindow* parent, wxWindowID id = SYMBOL_GALLERYALBUMIMAGEPANEL_IDNAME, const wxPoint& pos = SYMBOL_GALLERYALBUMIMAGEPANEL_POSITION, const wxSize& size = SYMBOL_GALLERYALBUMIMAGEPANEL_SIZE, long style = SYMBOL_GALLERYALBUMIMAGEPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_GALLERYALBUMIMAGEPANEL_IDNAME, const wxPoint& pos = SYMBOL_GALLERYALBUMIMAGEPANEL_POSITION, const wxSize& size = SYMBOL_GALLERYALBUMIMAGEPANEL_SIZE, long style = SYMBOL_GALLERYALBUMIMAGEPANEL_STYLE );

    /// Destructor
    ~GalleryImagePanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin GalleryImagePanel event handler declarations
    /// wxEVT_LEFT_UP event handler for ID_GALLERYALBUMIMAGEPANEL
    void OnLeftUp( wxMouseEvent& event );

    /// wxEVT_LEFT_DCLICK event handler for ID_GALLERYALBUMIMAGEPANEL
    void OnLeftDClick( wxMouseEvent& event );

    /// wxEVT_CONTEXT_MENU event handler for ID_GALLERYALBUMIMAGEPANEL
    void OnContextMenu( wxContextMenuEvent& event );

////@end GalleryImagePanel event handler declarations

////@begin GalleryImagePanel member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end GalleryImagePanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin GalleryImagePanel member variables
    wxStaticBitmap* m_bitmapCtrl;
    wxStaticText* m_ID;
    wxStaticText* m_title;
////@end GalleryImagePanel member variables
};

#endif
    // _GALLERYALBUMIMAGEPANEL_H_
