/////////////////////////////////////////////////////////////////////////////
// Name:        gui/GalleryPanel.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Mon 21 Feb 2022 17:10:35 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Mon 21 Feb 2022 17:10:35 CST

#ifndef _GALLERYPANEL_H_
#define _GALLERYPANEL_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxGridSizer;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_GALLERYPANEL 10000
#define ID_IMAGEGALLERYSCROLLEDWINDOW 10001
#define SYMBOL_GALLERYPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_GALLERYPANEL_TITLE _("GalleryPanel")
#define SYMBOL_GALLERYPANEL_IDNAME ID_GALLERYPANEL
#define SYMBOL_GALLERYPANEL_SIZE wxSize(400, 300)
#define SYMBOL_GALLERYPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * GalleryPanel class declaration
 */

class GalleryPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( GalleryPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    GalleryPanel();
    GalleryPanel( wxWindow* parent, wxWindowID id = SYMBOL_GALLERYPANEL_IDNAME, const wxPoint& pos = SYMBOL_GALLERYPANEL_POSITION, const wxSize& size = SYMBOL_GALLERYPANEL_SIZE, long style = SYMBOL_GALLERYPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_GALLERYPANEL_IDNAME, const wxPoint& pos = SYMBOL_GALLERYPANEL_POSITION, const wxSize& size = SYMBOL_GALLERYPANEL_SIZE, long style = SYMBOL_GALLERYPANEL_STYLE );

    /// Destructor
    ~GalleryPanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin GalleryPanel event handler declarations
////@end GalleryPanel event handler declarations

////@begin GalleryPanel member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end GalleryPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin GalleryPanel member variables
    wxScrolledWindow* m_scrolledWindow;
    wxGridSizer* m_sizer;
////@end GalleryPanel member variables
};

#endif
    // _GALLERYPANEL_H_
