/////////////////////////////////////////////////////////////////////////////
// Name:        GalleryImagePanel.cpp
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Mon 21 Feb 2022 17:10:36 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Mon 21 Feb 2022 17:10:36 CST

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "gui/GalleryImagePanel.h"

////@begin XPM images

////@end XPM images


/*
 * GalleryImagePanel type definition
 */

IMPLEMENT_DYNAMIC_CLASS( GalleryImagePanel, wxPanel )


/*
 * GalleryImagePanel event table definition
 */

BEGIN_EVENT_TABLE( GalleryImagePanel, wxPanel )

////@begin GalleryImagePanel event table entries
    EVT_LEFT_UP( GalleryImagePanel::OnLeftUp )
    EVT_LEFT_DCLICK( GalleryImagePanel::OnLeftDClick )
    EVT_CONTEXT_MENU( GalleryImagePanel::OnContextMenu )
////@end GalleryImagePanel event table entries

END_EVENT_TABLE()


/*
 * GalleryImagePanel constructors
 */

GalleryImagePanel::GalleryImagePanel()
{
    Init();
}

GalleryImagePanel::GalleryImagePanel( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, pos, size, style);
}


/*
 * GalleryImagePanel creator
 */

bool GalleryImagePanel::Create( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
////@begin GalleryImagePanel creation
    SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    wxPanel::Create( parent, id, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end GalleryImagePanel creation
    return true;
}


/*
 * GalleryImagePanel destructor
 */

GalleryImagePanel::~GalleryImagePanel()
{
////@begin GalleryImagePanel destruction
////@end GalleryImagePanel destruction
}


/*
 * Member initialisation
 */

void GalleryImagePanel::Init()
{
////@begin GalleryImagePanel member initialisation
    m_bitmapCtrl = NULL;
    m_ID = NULL;
    m_title = NULL;
////@end GalleryImagePanel member initialisation
}


/*
 * Control creation for GalleryImagePanel
 */

void GalleryImagePanel::CreateControls()
{    
////@begin GalleryImagePanel content construction
    // Generated by DialogBlocks, Mon 21 Feb 2022 17:10:36 CST (unregistered)

    GalleryImagePanel* itemPanel1 = this;

    wxBoxSizer* itemBoxSizer1 = new wxBoxSizer(wxVERTICAL);
    itemPanel1->SetSizer(itemBoxSizer1);

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer1->Add(itemBoxSizer2, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    m_bitmapCtrl = new wxStaticBitmap( itemPanel1, wxID_BITMAPSTATIC, wxNullBitmap, wxDefaultPosition, wxSize(100, 100), 0 );
    itemBoxSizer2->Add(m_bitmapCtrl, 1, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    m_ID = new wxStaticText( itemPanel1, wxID_IDSTATIC, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer1->Add(m_ID, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 0);

    m_title = new wxStaticText( itemPanel1, wxID_TITLESTATIC, wxEmptyString, wxDefaultPosition, wxSize(-1, 40), 0 );
    m_title->Wrap(90);
    itemBoxSizer1->Add(m_title, 1, wxALIGN_CENTER_HORIZONTAL|wxALL, 0);


    // Connect events and objects
    m_bitmapCtrl->Connect(wxID_BITMAPSTATIC, wxEVT_LEFT_UP, wxMouseEventHandler(GalleryImagePanel::OnLeftUp), NULL, this);
    m_bitmapCtrl->Connect(wxID_BITMAPSTATIC, wxEVT_LEFT_DCLICK, wxMouseEventHandler(GalleryImagePanel::OnLeftDClick), NULL, this);
    m_bitmapCtrl->Connect(wxID_BITMAPSTATIC, wxEVT_CONTEXT_MENU, wxContextMenuEventHandler(GalleryImagePanel::OnContextMenu), NULL, this);
////@end GalleryImagePanel content construction
}


/*
 * wxEVT_LEFT_UP event handler for ID_GALLERYIMAGEPANEL
 */

void GalleryImagePanel::OnLeftUp( wxMouseEvent& event )
{
////@begin wxEVT_LEFT_UP event handler for ID_GALLERYIMAGEPANEL in GalleryImagePanel.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_LEFT_UP event handler for ID_GALLERYIMAGEPANEL in GalleryImagePanel. 
}


/*
 * wxEVT_LEFT_DCLICK event handler for ID_GALLERYIMAGEPANEL
 */

void GalleryImagePanel::OnLeftDClick( wxMouseEvent& event )
{
////@begin wxEVT_LEFT_DCLICK event handler for ID_GALLERYIMAGEPANEL in GalleryImagePanel.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_LEFT_DCLICK event handler for ID_GALLERYIMAGEPANEL in GalleryImagePanel. 
}


/*
 * wxEVT_CONTEXT_MENU event handler for ID_GALLERYIMAGEPANEL
 */

void GalleryImagePanel::OnContextMenu( wxContextMenuEvent& event )
{
////@begin wxEVT_CONTEXT_MENU event handler for ID_GALLERYIMAGEPANEL in GalleryImagePanel.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_CONTEXT_MENU event handler for ID_GALLERYIMAGEPANEL in GalleryImagePanel. 
}


/*
 * Should we show tooltips?
 */

bool GalleryImagePanel::ShowToolTips()
{
    return true;
}

/*
 * Get bitmap resources
 */

wxBitmap GalleryImagePanel::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin GalleryImagePanel bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end GalleryImagePanel bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon GalleryImagePanel::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin GalleryImagePanel icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end GalleryImagePanel icon retrieval
}
