/////////////////////////////////////////////////////////////////////////////
// Name:        GenerateListSettings.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Fri 09 Dec 2022 14:55:49 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks ( unregistered ), Fri 09 Dec 2022 14:55:49 CST

#ifndef _GENERATELISTSETTINGS_H_
#define _GENERATELISTSETTINGS_H_


/*!
 * Includes
 */
#include "gui/GuiDefs.h"


 /*!
  * Forward declarations
  */

  /*!
   * Control identifiers
   */

   //// control identifiers

#define SYMBOL_GENERATELISTSETTINGS_STYLE wxCAPTION | wxRESIZE_BORDER | wxSYSTEM_MENU | wxCLOSE_BOX | wxTAB_TRAVERSAL
#define SYMBOL_GENERATELISTSETTINGS_TITLE _( "GenerateListSettings" )
#define SYMBOL_GENERATELISTSETTINGS_IDNAME ID_GENERATELISTSETTINGS
#define SYMBOL_GENERATELISTSETTINGS_SIZE wxSize( 400, 500 )
#define SYMBOL_GENERATELISTSETTINGS_POSITION wxDefaultPosition
//// control identifiers


/*!
 * GenerateListSettings class declaration
 */

class GenerateListSettings: public wxDialog
{
    DECLARE_DYNAMIC_CLASS( GenerateListSettings )
        DECLARE_EVENT_TABLE( )

public:
    enum GenerateListSettingsGuiDefs
    {
        ID_STATUSALLBUTTON = ID_GENERATELISTSETTINGS + 1,
        IDSTATUSCLEARBUTTON,
        ID_CHECKLISTBOX,
        ID_EMISSIONALLBUTTON,
        ID_EMISSIONCLEARBUTTON,
        ID_CHECKLISTBOX1,
        ID_FORMATALLBUTTON,
        ID_FORMATCLEARBUTTON,
        ID_CHECKLISTBOX2,
        ID_FROMYEARTEXTCTRL,
        ID_TOYEARTEXTCTRL,
        ID_CLEARYEARRANGEBUTTON
    };


    /// Constructors
    GenerateListSettings( );
    GenerateListSettings( wxWindow* parent, wxWindowID id = SYMBOL_GENERATELISTSETTINGS_IDNAME, const wxString& caption = SYMBOL_GENERATELISTSETTINGS_TITLE, const wxPoint& pos = SYMBOL_GENERATELISTSETTINGS_POSITION, const wxSize& size = SYMBOL_GENERATELISTSETTINGS_SIZE, long style = SYMBOL_GENERATELISTSETTINGS_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_GENERATELISTSETTINGS_IDNAME, const wxString& caption = SYMBOL_GENERATELISTSETTINGS_TITLE, const wxPoint& pos = SYMBOL_GENERATELISTSETTINGS_POSITION, const wxSize& size = SYMBOL_GENERATELISTSETTINGS_SIZE, long style = SYMBOL_GENERATELISTSETTINGS_STYLE );

    /// Destructor
    ~GenerateListSettings( );

    /// Initialises member variables
    void Init( );

    /// Creates the controls and sizers
    void CreateControls( );

    //// GenerateListSettings event handler declarations

        /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_STATUSALLBUTTON
    void OnStatusAllButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for IDSTATUSCLEARBUTTON
    void OnStatusClearButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_EMISSIONALLBUTTON
    void OnEmissionAllButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_EMISSIONCLEARBUTTON
    void OnEmissionClearButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_FORMATCLEARBUTTON
    void OnFormatClearButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_CLEARYEARRANGEBUTTON
    void OnClearYearRangeButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_OK
    void OnOkClick( wxCommandEvent& event );

    //// GenerateListSettings event handler declarations

    //// GenerateListSettings member function declarations

        /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
    //// GenerateListSettings member function declarations

        /// Should we show tooltips?
    static bool ShowToolTips( );

    int MakeBitPatern( wxArrayInt& array );

    int GetCheckedStatusItems( );
    void SetCheckedStatusItems( int checkedStatusItems );
    int GetCheckedFormatItems( );
    void SetCheckedFormatItems( int checkedFormatItems );
    int GetCheckedEmissionItems( );
    void SetCheckedEmissionItems( int checkedEmissionItems );

    wxString GetFromYear( ) { return m_fromYear->GetValue( ); };
    void SetFromYear( wxString year ) { m_fromYear->SetValue( year ); };
    wxString GetToYear( ) { return m_toYear->GetValue( ); };
    void SetToYear( wxString year ) { m_toYear->SetValue( year ); };

    wxCheckListBox* m_statusListCtrl;
    wxArrayString m_statusListCtrlStrings;

    wxCheckListBox* m_emissionListCtrl;
    wxArrayString m_emissionListCtrlStrings;

    wxCheckListBox* m_formatListCtrl;
    wxArrayString m_formatListCtrlStrings;

    wxTextCtrl* m_fromYear;
    wxTextCtrl* m_toYear;


};

#endif
// _GENERATELISTSETTINGS_H_
