/////////////////////////////////////////////////////////////////////////////
// Name:        GenerateListSettings.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Fri 09 Dec 2022 14:55:49 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Fri 09 Dec 2022 14:55:49 CST

#ifndef _GENERATELISTSETTINGS_H_
#define _GENERATELISTSETTINGS_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_GENERATELISTSETTINGS 10000
#define ID_STATUSALLBUTTON 10005
#define IDSTATUSCLEARBUTTON 10006
#define ID_CHECKLISTBOX 10003
#define ID_EMISSIONALLBUTTON 10007
#define ID_EMISSIONCLEARBUTTON 10008
#define ID_CHECKLISTBOX1 10002
#define ID_FORMATALLBUTTON 10001
#define ID_FORMATCLEARBUTTON 10009
#define ID_CHECKLISTBOX2 10004
#define ID_FROMYEARTEXTCTRL 10010
#define ID_TOYEARTEXTCTRL 10011
#define ID_CLEARYEARRANGEBUTTON 10012
#define SYMBOL_GENERATELISTSETTINGS_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_GENERATELISTSETTINGS_TITLE _("GenerateListSettings")
#define SYMBOL_GENERATELISTSETTINGS_IDNAME ID_GENERATELISTSETTINGS
#define SYMBOL_GENERATELISTSETTINGS_SIZE wxSize(400, 500)
#define SYMBOL_GENERATELISTSETTINGS_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * GenerateListSettings class declaration
 */

class GenerateListSettings: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( GenerateListSettings )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    GenerateListSettings();
    GenerateListSettings( wxWindow* parent, wxWindowID id = SYMBOL_GENERATELISTSETTINGS_IDNAME, const wxString& caption = SYMBOL_GENERATELISTSETTINGS_TITLE, const wxPoint& pos = SYMBOL_GENERATELISTSETTINGS_POSITION, const wxSize& size = SYMBOL_GENERATELISTSETTINGS_SIZE, long style = SYMBOL_GENERATELISTSETTINGS_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_GENERATELISTSETTINGS_IDNAME, const wxString& caption = SYMBOL_GENERATELISTSETTINGS_TITLE, const wxPoint& pos = SYMBOL_GENERATELISTSETTINGS_POSITION, const wxSize& size = SYMBOL_GENERATELISTSETTINGS_SIZE, long style = SYMBOL_GENERATELISTSETTINGS_STYLE );

    /// Destructor
    ~GenerateListSettings();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin GenerateListSettings event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_STATUSALLBUTTON
    void OnStatusAllButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for IDSTATUSCLEARBUTTON
    void OnStatusClearButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_EMISSIONALLBUTTON
    void OnEmissionAllButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_EMISSIONCLEARBUTTON
    void OnEmissionClearButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_FORMATCLEARBUTTON
    void OnFormatClearButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_CLEARYEARRANGEBUTTON
    void OnClearYearRangeButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_OK
    void OnOkClick( wxCommandEvent& event );

////@end GenerateListSettings event handler declarations

////@begin GenerateListSettings member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end GenerateListSettings member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

    int MakeBitPatern( wxArrayInt& array );

    int GetCheckedStatusItems(  );
    void SetCheckedStatusItems( int checkedStatusItems );
    int GetCheckedFormatItems(  );
    void SetCheckedFormatItems( int checkedFormatItems );
    int GetCheckedEmissionItems( );
    void SetCheckedEmissionItems( int checkedEmissionItems );

    wxString GetFromYear() { return m_fromYear->GetValue(); };
    void SetFromYear(wxString year){ m_fromYear->SetValue( year ); };
    wxString GetToYear( ) { return m_toYear->GetValue(); };
    void SetToYear(wxString year){ m_toYear->SetValue( year ); };

    wxCheckListBox* m_statusListCtrl;
    wxArrayString m_statusListCtrlStrings;

    wxCheckListBox* m_emissionListCtrl;
    wxArrayString m_emissionListCtrlStrings;

    wxCheckListBox* m_formatListCtrl;
    wxArrayString m_formatListCtrlStrings;

    wxTextCtrl* m_fromYear;
    wxTextCtrl* m_toYear;


};

#endif
    // _GENERATELISTSETTINGS_H_
