/////////////////////////////////////////////////////////////////////////////
// Name:        StampDetailsDialog.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Sun 27 Mar 2022 11:03:21 CDT
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Sun 27 Mar 2022 11:03:21 CDT

#ifndef _STAMPDETAILSDIALOG_H_
#define _STAMPDETAILSDIALOG_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/listctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class LabeledTextBox;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_STAMPDETAILSDIALOG 10000
#define ID_IDLABELTEXTBOX 10007
#define ID_NAMELABELEDTEXTBOX 10009
#define ID_HEIGHTLABELEDTEXTBOX 10001
#define ID_WIDTHLABELEDTEXTBOX 10002
#define ID_BUTTON 10005
#define ID_BUTTON3 10008
#define ID_LISTCTRL 10006
#define SYMBOL_STAMPDETAILSDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_STAMPDETAILSDIALOG_TITLE _("StampDetailsDialog")
#define SYMBOL_STAMPDETAILSDIALOG_IDNAME ID_STAMPDETAILSDIALOG
#define SYMBOL_STAMPDETAILSDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_STAMPDETAILSDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * StampDetailsDialog class declaration
 */

class StampDetailsDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( StampDetailsDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    StampDetailsDialog();
    StampDetailsDialog( wxWindow* parent, wxWindowID id = SYMBOL_STAMPDETAILSDIALOG_IDNAME, const wxString& caption = SYMBOL_STAMPDETAILSDIALOG_TITLE, const wxPoint& pos = SYMBOL_STAMPDETAILSDIALOG_POSITION, const wxSize& size = SYMBOL_STAMPDETAILSDIALOG_SIZE, long style = SYMBOL_STAMPDETAILSDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_STAMPDETAILSDIALOG_IDNAME, const wxString& caption = SYMBOL_STAMPDETAILSDIALOG_TITLE, const wxPoint& pos = SYMBOL_STAMPDETAILSDIALOG_POSITION, const wxSize& size = SYMBOL_STAMPDETAILSDIALOG_SIZE, long style = SYMBOL_STAMPDETAILSDIALOG_STYLE );

    /// Destructor
    ~StampDetailsDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin StampDetailsDialog event handler declarations

////@end StampDetailsDialog event handler declarations

////@begin StampDetailsDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end StampDetailsDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();
void SetHeight(wxString height){m_height->SetValue(height);};
void SetWidth(wxString width){m_width->SetValue(width);};
void SetID(wxString id){m_id->SetValue(id);};
void SetName(wxString name){m_name->SetValue(name);};
wxString GetHeight( ){return m_height->GetValue();};
wxString GetWidth( ){return m_width->GetValue();};
wxString GetID( ){return m_id->GetValue();};
wxString GetName( ){return m_name->GetValue();};
bool IsNameModified(){return m_name->IsModified();};
bool IsIDModified(){return m_id->IsModified();};
bool IsHeightModified(){return m_height->IsModified();};
bool IsWidthModified(){return m_widget->IsModified();};
////@begin StampDetailsDialog member variables
    LabeledTextBox* m_id;
    LabeledTextBox* m_name;
    LabeledTextBox* m_height;
    LabeledTextBox* m_width;
////@end StampDetailsDialog member variables
};

#endif
    // _STAMPDETAILSDIALOG_H_
