/**
 * @file FilterDialog.h
 * @author Eddie Monroe ()
 * @brief 
 * @version 0.1
 * @date 2021-02-25
 * 
 * @copyright Copyright (c) 2021 
 * 
 * This file is part of AlbumGenerator.
 *
 * AlbumGenerator is free software: you can redistribute it and/or modify it under the 
 * terms of the GNU General Public License as published by the Free Software Foundation, 
 * either version 3 of the License, or any later version.
 *
 * AlbumGenerator is distributed in the hope that it will be useful, but WITHOUT ANY 
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with 
 * AlbumGenerator. If not, see <https://www.gnu.org/licenses/>.
 * 
 **************************************************/


#ifndef _FILTER_H_
#define _FILTER_H_

/*
 * Includes
 */

 
 

 
#define ID_CHOICE ID_FILTER+1
#define ID_CHOICE1 ID_FILTER+2
#define ID_CHECKLISTBOX1 ID_FILTER+3
#define ID_CHECKLISTBOX ID_FILTER+4
#define SYMBOL_FILTERDIALOG_STYLE                                              \
    wxCAPTION | wxRESIZE_BORDER | wxSYSTEM_MENU | wxCLOSE_BOX | wxTAB_TRAVERSAL
#define SYMBOL_FILTERDIALOG_TITLE _( "Filter" )
#define SYMBOL_FILTERDIALOG_IDNAME ID_FILTER
#define SYMBOL_FILTERDIALOG_SIZE wxSize( 400, 300 )
#define SYMBOL_FILTERDIALOG_POSITION wxDefaultPosition
 

/*!
 * FilterDialog class declaration
 */

class FilterDialog : public wxDialog
{
    DECLARE_DYNAMIC_CLASS( FilterDialog )
    DECLARE_EVENT_TABLE( )

  public:
    // Constructors
    /**
     * @brief Default Constructor for a new FilterDialog object
     * 
     **************************************************/
    FilterDialog( );

    /**
     * @brief Construct a new FilterDialog object
     * 
     * @param  parent	The parent window.
     * @param  id	An identifier for the panel. wxID_ANY is taken to mean a default.
     * @param  pos	The panel position. The value wxDefaultPosition indicates a default position, chosen by either the windowing system or wxWidgets, depending on platform.
     * @param  size	The panel size. The value wxDefaultSize indicates a default size, chosen by either the windowing system or wxWidgets, depending on platform.
     * @param  style	The window style. 
     * @see wxPanel.
     **************************************************/
    FilterDialog( wxWindow *parent, wxWindowID id = SYMBOL_FILTERDIALOG_IDNAME,
                  const wxString &caption = SYMBOL_FILTERDIALOG_TITLE,
                  const wxPoint &pos = SYMBOL_FILTERDIALOG_POSITION,
                  const wxSize &size = SYMBOL_FILTERDIALOG_SIZE,
                  long style = SYMBOL_FILTERDIALOG_STYLE );

    /**
     * @brief  Used for two-step panel construction.
     * Use with default constructor.
     * 
     * @param  parent	The parent window.
     * @param  id	An identifier for the panel. wxID_ANY is taken to mean a default.
     * @param  pos	The panel position. The value wxDefaultPosition indicates a default position, chosen by either the windowing system or wxWidgets, depending on platform.
     * @param  size	The panel size. The value wxDefaultSize indicates a default size, chosen by either the windowing system or wxWidgets, depending on platform.
     * @param  style	The window style. 
     * @return bool 
     * 
     **************************************************/
    bool Create( wxWindow *parent, wxWindowID id = SYMBOL_FILTERDIALOG_IDNAME,
                 const wxString &caption = SYMBOL_FILTERDIALOG_TITLE,
                 const wxPoint &pos = SYMBOL_FILTERDIALOG_POSITION,
                 const wxSize &size = SYMBOL_FILTERDIALOG_SIZE,
                 long style = SYMBOL_FILTERDIALOG_STYLE );

    // Destructor
    ~FilterDialog( );

        /**
     * @brief   Initialises member variables
     * 
     **************************************************/
    void Init( );

    /**
     * @brief Creates the controls and sizers
     * 
     **************************************************/
    void CreateControls( );

     // FilterDialog event handler declarations

    // wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE
    void OnChoiceSelected( wxCommandEvent &event );

    // wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE1
    void OnChoice1Selected( wxCommandEvent &event );

    // wxEVT_COMMAND_LISTBOX_DOUBLECLICKED event handler for ID_CHECKLISTBOX1
    void OnChecklistbox1DoubleClicked( wxCommandEvent &event );

    // wxEVT_COMMAND_LISTBOX_DOUBLECLICKED event handler for ID_CHECKLISTBOX
    void OnChecklistboxDoubleClicked( wxCommandEvent &event );

     // FilterDialog event handler declarations

     // FilterDialog member function declarations

    /**
     * @brief Retrieves bitmap resources
     * 
     * @param  name (autogenerated. Dummy.)
     * @return wxBitmap null
     **************************************************/
    wxBitmap GetBitmapResource( const wxString &name );

    // Retrieves icon resources
    wxIcon GetIconResource( const wxString &name );
     // FilterDialog member function declarations

    // Should we show tooltips?
    static bool ShowToolTips( );

     // FilterDialog member variables
     // FilterDialog member variables
};

#endif
// _FILTER_H_
