/////////////////////////////////////////////////////////////////////////////
// Name:        AbumGeneratorDialog.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Sun 16 Jan 2022 19:17:13 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Sun 16 Jan 2022 19:17:13 CST

#ifndef _ABUMGENERATORDIALOG_H_
#define _ABUMGENERATORDIALOG_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/splitter.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxSplitterWindow;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ABUMGENERATORDIALOG 10000
#define ID_PRIMARYSPLITTERWINDOW 13001
#define ID_CHECKLISTBOX 10002
#define ID_SECONDARYSPLITTERWINDOW 13005
#define ID_AECMDLISTBOX 10006
#define ID_RICHTEXTTEXTCTRL 10004
#define ID_BUTTON 10001
#define SYMBOL_ABUMGENERATORDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_ABUMGENERATORDIALOG_TITLE _("AbumGeneratorDialog")
#define SYMBOL_ABUMGENERATORDIALOG_IDNAME ID_ABUMGENERATORDIALOG
#define SYMBOL_ABUMGENERATORDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_ABUMGENERATORDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * AbumGeneratorDialog class declaration
 */

class AbumGeneratorDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( AbumGeneratorDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    AbumGeneratorDialog();
    AbumGeneratorDialog( wxWindow* parent, wxWindowID id = SYMBOL_ABUMGENERATORDIALOG_IDNAME, const wxString& caption = SYMBOL_ABUMGENERATORDIALOG_TITLE, const wxPoint& pos = SYMBOL_ABUMGENERATORDIALOG_POSITION, const wxSize& size = SYMBOL_ABUMGENERATORDIALOG_SIZE, long style = SYMBOL_ABUMGENERATORDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ABUMGENERATORDIALOG_IDNAME, const wxString& caption = SYMBOL_ABUMGENERATORDIALOG_TITLE, const wxPoint& pos = SYMBOL_ABUMGENERATORDIALOG_POSITION, const wxSize& size = SYMBOL_ABUMGENERATORDIALOG_SIZE, long style = SYMBOL_ABUMGENERATORDIALOG_STYLE );

    /// Destructor
    ~AbumGeneratorDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin AbumGeneratorDialog event handler declarations

    /// wxEVT_RIGHT_UP event handler for ID_CHECKLISTBOX
    void OnRightUp( wxMouseEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON
    void OnButtonClick( wxCommandEvent& event );

////@end AbumGeneratorDialog event handler declarations

////@begin AbumGeneratorDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end AbumGeneratorDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin AbumGeneratorDialog member variables
    wxSplitterWindow* m_primarySplitterWindow;
    wxCheckListBox* m_itemListBox;
    wxSplitterWindow* m_secondarySplitterWindow;
    wxTextCtrl* m_richTextCtrl;
////@end AbumGeneratorDialog member variables
};

#endif
    // _ABUMGENERATORDIALOG_H_
