var annotated_dup =
[
    [ "Catalog", "namespace_catalog.html", [
      [ "CatalogBase", "class_catalog_1_1_catalog_base.html", "class_catalog_1_1_catalog_base" ],
      [ "CatalogCode", "class_catalog_1_1_catalog_code.html", "class_catalog_1_1_catalog_code" ],
      [ "CatalogData", "class_catalog_1_1_catalog_data.html", "class_catalog_1_1_catalog_data" ],
      [ "CatalogList", "class_catalog_1_1_catalog_list.html", "class_catalog_1_1_catalog_list" ],
      [ "CatalogVolume", "class_catalog_1_1_catalog_volume.html", "class_catalog_1_1_catalog_volume" ],
      [ "Entry", "class_catalog_1_1_entry.html", "class_catalog_1_1_entry" ],
      [ "InventoryItem", "class_catalog_1_1_inventory_item.html", "class_catalog_1_1_inventory_item" ],
      [ "MergeData", "class_catalog_1_1_merge_data.html", "class_catalog_1_1_merge_data" ],
      [ "MergeList", "class_catalog_1_1_merge_list.html", "class_catalog_1_1_merge_list" ],
      [ "MountCSVData", "class_catalog_1_1_mount_c_s_v_data.html", "class_catalog_1_1_mount_c_s_v_data" ],
      [ "Mounts", "struct_catalog_1_1_mounts.html", "struct_catalog_1_1_mounts" ],
      [ "StampMountData", "class_catalog_1_1_stamp_mount_data.html", "class_catalog_1_1_stamp_mount_data" ]
    ] ],
    [ "Design", "namespace_design.html", [
      [ "Album", "class_design_1_1_album.html", "class_design_1_1_album" ],
      [ "AlbumBase", "class_design_1_1_album_base.html", "class_design_1_1_album_base" ],
      [ "AlbumData", "class_design_1_1_album_data.html", "class_design_1_1_album_data" ],
      [ "AlbumList", "class_design_1_1_album_list.html", "class_design_1_1_album_list" ],
      [ "AlbumVolume", "class_design_1_1_album_volume.html", "class_design_1_1_album_volume" ],
      [ "Attribute", "class_design_1_1_attribute.html", "class_design_1_1_attribute" ],
      [ "Column", "class_design_1_1_column.html", "class_design_1_1_column" ],
      [ "Defaults", "class_design_1_1_defaults.html", "class_design_1_1_defaults" ],
      [ "Frame", "class_design_1_1_frame.html", "class_design_1_1_frame" ],
      [ "FrameDefaults", "class_design_1_1_frame_defaults.html", "class_design_1_1_frame_defaults" ],
      [ "LabelFrame", "class_design_1_1_label_frame.html", "class_design_1_1_label_frame" ],
      [ "LayoutBase", "class_design_1_1_layout_base.html", "class_design_1_1_layout_base" ],
      [ "Page", "class_design_1_1_page.html", "class_design_1_1_page" ],
      [ "PageDefaults", "class_design_1_1_page_defaults.html", "class_design_1_1_page_defaults" ],
      [ "Row", "class_design_1_1_row.html", "class_design_1_1_row" ],
      [ "Stamp", "class_design_1_1_stamp.html", "class_design_1_1_stamp" ],
      [ "StampDefaults", "class_design_1_1_stamp_defaults.html", "class_design_1_1_stamp_defaults" ],
      [ "TextBox", "class_design_1_1_text_box.html", "class_design_1_1_text_box" ],
      [ "TitleFrame", "class_design_1_1_title_frame.html", "class_design_1_1_title_frame" ],
      [ "XMLBase", "class_design_1_1_x_m_l_base.html", "class_design_1_1_x_m_l_base" ]
    ] ],
    [ "Inventory", "namespace_inventory.html", [
      [ "Collection", "class_inventory_1_1_collection.html", "class_inventory_1_1_collection" ],
      [ "CollectionData", "class_inventory_1_1_collection_data.html", "class_inventory_1_1_collection_data" ],
      [ "CollectionList", "class_inventory_1_1_collection_list.html", "class_inventory_1_1_collection_list" ]
    ] ],
    [ "Utils", "namespace_utils.html", [
      [ "CSVData", "class_utils_1_1_c_s_v_data.html", "class_utils_1_1_c_s_v_data" ],
      [ "Font", "class_utils_1_1_font.html", "class_utils_1_1_font" ],
      [ "FontList", "class_utils_1_1_font_list.html", "class_utils_1_1_font_list" ],
      [ "Project", "class_utils_1_1_project.html", "class_utils_1_1_project" ],
      [ "Settings", "class_utils_1_1_settings.html", "class_utils_1_1_settings" ],
      [ "StampLink", "class_utils_1_1_stamp_link.html", "class_utils_1_1_stamp_link" ],
      [ "StampList", "class_utils_1_1_stamp_list.html", "class_utils_1_1_stamp_list" ],
      [ "TOCBase", "class_utils_1_1_t_o_c_base.html", "class_utils_1_1_t_o_c_base" ],
      [ "Volume", "class_utils_1_1_volume.html", "class_utils_1_1_volume" ],
      [ "VolumeList", "class_utils_1_1_volume_list.html", "class_utils_1_1_volume_list" ],
      [ "XMLIterator", "class_utils_1_1_x_m_l_iterator.html", "class_utils_1_1_x_m_l_iterator" ]
    ] ],
    [ "AlbumDetailsPanel", "class_album_details_panel.html", "class_album_details_panel" ],
    [ "AlbumImagePanel", "class_album_image_panel.html", "class_album_image_panel" ],
    [ "AlbumPanel", "class_album_panel.html", "class_album_panel" ],
    [ "AlbumTOCTreeCtrl", "class_album_t_o_c_tree_ctrl.html", "class_album_t_o_c_tree_ctrl" ],
    [ "AlbumTreeCtrl", "class_album_tree_ctrl.html", "class_album_tree_ctrl" ],
    [ "AlbumTreePanel", "class_album_tree_panel.html", "class_album_tree_panel" ],
    [ "AppData", "class_app_data.html", "class_app_data" ],
    [ "CatalogDetailsDialog", "class_catalog_details_dialog.html", "class_catalog_details_dialog" ],
    [ "CatalogPanel", "class_catalog_panel.html", "class_catalog_panel" ],
    [ "CatalogTOCTreeCtrl", "class_catalog_t_o_c_tree_ctrl.html", "class_catalog_t_o_c_tree_ctrl" ],
    [ "CatalogTreeCtrl", "class_catalog_tree_ctrl.html", "class_catalog_tree_ctrl" ],
    [ "CatalogTreeItemData", "class_catalog_tree_item_data.html", "class_catalog_tree_item_data" ],
    [ "CharacteristicsPanel", "class_characteristics_panel.html", "class_characteristics_panel" ],
    [ "ColDetailsPanel", "class_col_details_panel.html", "class_col_details_panel" ],
    [ "ComparePanel", "class_compare_panel.html", "class_compare_panel" ],
    [ "CompareTreeCtrl", "class_compare_tree_ctrl.html", "class_compare_tree_ctrl" ],
    [ "CompareTreeItemData", "class_compare_tree_item_data.html", "class_compare_tree_item_data" ],
    [ "CompEntry", "class_comp_entry.html", "class_comp_entry" ],
    [ "DebugString", "class_debug_string.html", "class_debug_string" ],
    [ "DefinePeriodsPanel", "class_define_periods_panel.html", "class_define_periods_panel" ],
    [ "DesignTreeItemData", "class_design_tree_item_data.html", "class_design_tree_item_data" ],
    [ "ExportDialog", "class_export_dialog.html", "class_export_dialog" ],
    [ "ExportPanel", "class_export_panel.html", "class_export_panel" ],
    [ "FileCreateDialog", "class_file_create_dialog.html", "class_file_create_dialog" ],
    [ "FontDefaultsPanel", "class_font_defaults_panel.html", "class_font_defaults_panel" ],
    [ "FontPicker", "class_font_picker.html", "class_font_picker" ],
    [ "FrameDefaultsPanel", "class_frame_defaults_panel.html", "class_frame_defaults_panel" ],
    [ "GenerateList", "class_generate_list.html", "class_generate_list" ],
    [ "GenerateListSettings", "class_generate_list_settings.html", "class_generate_list_settings" ],
    [ "HelperPanel", "class_helper_panel.html", "class_helper_panel" ],
    [ "IdentificationPanel", "class_identification_panel.html", "class_identification_panel" ],
    [ "ImageGalleryPanel", "class_image_gallery_panel.html", "class_image_gallery_panel" ],
    [ "ImagePanel", "class_image_panel.html", "class_image_panel" ],
    [ "InventoryPanel", "class_inventory_panel.html", "class_inventory_panel" ],
    [ "LabeledTextBox", "class_labeled_text_box.html", "class_labeled_text_box" ],
    [ "NewStampDialog", "class_new_stamp_dialog.html", "class_new_stamp_dialog" ],
    [ "PageDefaultsPanel", "class_page_defaults_panel.html", "class_page_defaults_panel" ],
    [ "PageDetailsPanel", "class_page_details_panel.html", "class_page_details_panel" ],
    [ "PreferencesDialog", "class_preferences_dialog.html", "class_preferences_dialog" ],
    [ "RealRect", "class_real_rect.html", "class_real_rect" ],
    [ "RemoveVolumeDialog", "class_remove_volume_dialog.html", "class_remove_volume_dialog" ],
    [ "RowDetailsPanel", "class_row_details_panel.html", "class_row_details_panel" ],
    [ "SortOrderPanel", "class_sort_order_panel.html", "class_sort_order_panel" ],
    [ "StampDefaultsPanel", "class_stamp_defaults_panel.html", "class_stamp_defaults_panel" ],
    [ "StampDescriptionPanel", "class_stamp_description_panel.html", "class_stamp_description_panel" ],
    [ "StampDetailsPanel", "class_stamp_details_panel.html", "class_stamp_details_panel" ],
    [ "StampToolApp", "class_stamp_tool_app.html", "class_stamp_tool_app" ],
    [ "StampToolFrame", "class_stamp_tool_frame.html", "class_stamp_tool_frame" ],
    [ "StampToolPanel", "class_stamp_tool_panel.html", "class_stamp_tool_panel" ],
    [ "TitleHelper", "class_title_helper.html", "class_title_helper" ],
    [ "TOCTreeCtrl", "class_t_o_c_tree_ctrl.html", "class_t_o_c_tree_ctrl" ],
    [ "TOCTreeItemData", "class_t_o_c_tree_item_data.html", "class_t_o_c_tree_item_data" ]
];