var dir_3a314dc41d848bce28e699d1264bd838 =
[
    [ "Album.cpp", "_album_8cpp.html", null ],
    [ "Album.h", "_album_8h.html", "_album_8h" ],
    [ "AlbumBase.cpp", "_album_base_8cpp.html", null ],
    [ "AlbumBase.h", "_album_base_8h.html", "_album_base_8h" ],
    [ "AlbumData.cpp", "_album_data_8cpp.html", null ],
    [ "AlbumData.h", "_album_data_8h.html", "_album_data_8h" ],
    [ "AlbumList.cpp", "_album_list_8cpp.html", null ],
    [ "AlbumList.h", "_album_list_8h.html", "_album_list_8h" ],
    [ "AlbumVolume.cpp", "_album_volume_8cpp.html", null ],
    [ "AlbumVolume.h", "_album_volume_8h.html", "_album_volume_8h" ],
    [ "Attribute (copy 1).h", "_attribute_01_07copy_011_08_8h.html", "_attribute_01_07copy_011_08_8h" ],
    [ "Attribute.h", "_attribute_8h.html", "_attribute_8h" ],
    [ "Column.cpp", "_column_8cpp.html", null ],
    [ "Column.h", "_column_8h.html", "_column_8h" ],
    [ "Defaults.cpp", "_defaults_8cpp.html", null ],
    [ "Defaults.h", "_defaults_8h.html", "_defaults_8h" ],
    [ "DesignDefs.cpp", "_design_defs_8cpp.html", "_design_defs_8cpp" ],
    [ "DesignDefs.h", "_design_defs_8h.html", "_design_defs_8h" ],
    [ "Frame.cpp", "_frame_8cpp.html", "_frame_8cpp" ],
    [ "Frame.h", "_frame_8h.html", "_frame_8h" ],
    [ "FrameDefaults.cpp", "_frame_defaults_8cpp.html", null ],
    [ "FrameDefaults.h", "_frame_defaults_8h.html", "_frame_defaults_8h" ],
    [ "LabelFrame.cpp", "_label_frame_8cpp.html", null ],
    [ "LabelFrame.h", "_label_frame_8h.html", "_label_frame_8h" ],
    [ "LayoutBase.cpp", "_layout_base_8cpp.html", null ],
    [ "LayoutBase.h", "_layout_base_8h.html", "_layout_base_8h" ],
    [ "Page.cpp", "_page_8cpp.html", null ],
    [ "Page.h", "_page_8h.html", "_page_8h" ],
    [ "PageDefaults.cpp", "_page_defaults_8cpp.html", null ],
    [ "PageDefaults.h", "_page_defaults_8h.html", "_page_defaults_8h" ],
    [ "Row.cpp", "_row_8cpp.html", null ],
    [ "Row.h", "_row_8h.html", "_row_8h" ],
    [ "Stamp.cpp", "_stamp_8cpp.html", "_stamp_8cpp" ],
    [ "Stamp.h", "_stamp_8h.html", "_stamp_8h" ],
    [ "StampDefaults.cpp", "_stamp_defaults_8cpp.html", null ],
    [ "StampDefaults.h", "_stamp_defaults_8h.html", "_stamp_defaults_8h" ],
    [ "TextBox.cpp", "_text_box_8cpp.html", null ],
    [ "TextBox.h", "_text_box_8h.html", "_text_box_8h" ],
    [ "TitleFrame.cpp", "_title_frame_8cpp.html", null ],
    [ "TitleFrame.h", "_title_frame_8h.html", "_title_frame_8h" ],
    [ "XMLBase.cpp", "_x_m_l_base_8cpp.html", null ],
    [ "XMLBase.h", "_x_m_l_base_8h.html", "_x_m_l_base_8h" ]
];