/////////////////////////////////////////////////////////////////////////////
// Name:        CharacteristicsPanel.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Sat 23 Apr 2022 14:51:54 CDT
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Sat 23 Apr 2022 14:51:54 CDT

#ifndef _CHARACTERISTICSPANEL_H_
#define _CHARACTERISTICSPANEL_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/cshelp.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class LabeledTextBox;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CHARACTERISTICSANEL 10000
#define ID_FACETEXTBOX 10005
#define ID_CURRENCYTEXTBOX 10006
#define ID_HEIGHTEXTBOX 10012
#define ID_WIDTHTEXTBOX 10013
#define ID_PERFORATIONTEXTBOX 10006
#define ID_WATERMARKEXTBOX 10008
#define ID_GUMTEXTBOX 10007
#define ID_VARIANTTEXTBOX 10010
#define ID_COLORSTEXTBOX 10014
#define ID_PAPERTEXTBOX 10005
#define ID_PRINTINGTEXTBOX 10001
#define ID_PRINTRUNTEXTBOX 10009
#define ID_EXPIRYDATEEXTBOX 10008
#define SYMBOL_CHARACTERISTICSPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_CHARACTERISTICSPANEL_TITLE _("CharacteristicsPanel")
#define SYMBOL_CHARACTERISTICSPANEL_IDNAME ID_CHARACTERISTICSANEL
#define SYMBOL_CHARACTERISTICSPANEL_SIZE wxSize(400, 300)
#define SYMBOL_CHARACTERISTICSPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * CharacteristicsPanel class declaration
 */

class CharacteristicsPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( CharacteristicsPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CharacteristicsPanel();
    CharacteristicsPanel( wxWindow* parent, wxWindowID id = SYMBOL_CHARACTERISTICSPANEL_IDNAME, const wxPoint& pos = SYMBOL_CHARACTERISTICSPANEL_POSITION, const wxSize& size = SYMBOL_CHARACTERISTICSPANEL_SIZE, long style = SYMBOL_CHARACTERISTICSPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CHARACTERISTICSPANEL_IDNAME, const wxPoint& pos = SYMBOL_CHARACTERISTICSPANEL_POSITION, const wxSize& size = SYMBOL_CHARACTERISTICSPANEL_SIZE, long style = SYMBOL_CHARACTERISTICSPANEL_STYLE );

    /// Destructor
    ~CharacteristicsPanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CharacteristicsPanel event handler declarations
////@end CharacteristicsPanel event handler declarations

////@begin CharacteristicsPanel member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CharacteristicsPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin CharacteristicsPanel member variables
    LabeledTextBox* m_faceValue;
    LabeledTextBox* m_currency;
    LabeledTextBox* m_height;
    LabeledTextBox* m_width;
    LabeledTextBox* m_perforation;
    LabeledTextBox* m_watermark;
    LabeledTextBox* m_gum;
    LabeledTextBox* m_variant;
    LabeledTextBox* m_colors;
    LabeledTextBox* m_paper;
    LabeledTextBox* m_printing;
    LabeledTextBox* m_printRun;
    LabeledTextBox* m_expiryDate;
////@end CharacteristicsPanel member variables
};

#endif
    // _CHARACTERISTICSPANEL_H_
