/////////////////////////////////////////////////////////////////////////////
// Name:        DescriptionPanel.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Sat 23 Apr 2022 13:03:23 CDT
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Sat 23 Apr 2022 13:03:23 CDT

#ifndef _DESCRIPTIONPANEL_H_
#define _DESCRIPTIONPANEL_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/splitter.h"
#include "wx/notebook.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class IdentificationPanel;
class ImagePanel;
class InventoryPanel;
class CharacteristicsPanel;
class MiscellaneousDataPanel;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DESCRIPTIONPANEL 10000
#define ID_NOTEBOOKSPLITTERWINDOW 10013
#define ID_DESCRIPTIONSPLITTERWINDOW 10012
#define ID_IDENTIFICATIONPANELFORIEGN 10006
#define ID_PANEL 10002
#define ID_ZOOMSLIDER 10011
#define ID_STAMPIMAGEPANEL 10008
#define ID_NOTEBOOK 10001
#define ID_INVENTORYFOREIGN 10003
#define ID_CHARACTERISTICSWINDOW 10004
#define ID_MISCELLANEOUSDATAFORIEGN 10009
#define ID_DESCRIPTIONSCROLLEDWINDOW 10003
#define ID_DESCRIPTIONTEXTCTRL 10002
#define ID_BACKGROUNDPANEL1 10010
#define ID_BKGNDSCROLLEDWINDOW 10007
#define ID_BKGNDTEXTCTRL 10005
#define SYMBOL_DESCRIPTIONPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_DESCRIPTIONPANEL_TITLE _("DescriptionPanel")
#define SYMBOL_DESCRIPTIONPANEL_IDNAME ID_DESCRIPTIONPANEL
#define SYMBOL_DESCRIPTIONPANEL_SIZE wxDefaultSize
#define SYMBOL_DESCRIPTIONPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * DescriptionPanel class declaration
 */

class DescriptionPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( DescriptionPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    DescriptionPanel();
    DescriptionPanel( wxWindow* parent, wxWindowID id = SYMBOL_DESCRIPTIONPANEL_IDNAME, const wxPoint& pos = SYMBOL_DESCRIPTIONPANEL_POSITION, const wxSize& size = SYMBOL_DESCRIPTIONPANEL_SIZE, long style = SYMBOL_DESCRIPTIONPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_DESCRIPTIONPANEL_IDNAME, const wxPoint& pos = SYMBOL_DESCRIPTIONPANEL_POSITION, const wxSize& size = SYMBOL_DESCRIPTIONPANEL_SIZE, long style = SYMBOL_DESCRIPTIONPANEL_STYLE );

    /// Destructor
    ~DescriptionPanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin DescriptionPanel event handler declarations
    /// wxEVT_COMMAND_SLIDER_UPDATED event handler for ID_ZOOMSLIDER
    void OnZoomsliderUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_DESCRIPTIONTEXTCTRL
    void OnDescriptionTextctrlTextUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_BKGNDTEXTCTRL
    void OnBkGndTextUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_MAXLEN event handler for ID_BKGNDTEXTCTRL
    void OnBkgndtextctrlMaxLen( wxCommandEvent& event );

    /// wxEVT_LEAVE_WINDOW event handler for ID_BKGNDTEXTCTRL
    void OnLeaveWindow( wxMouseEvent& event );

////@end DescriptionPanel event handler declarations

////@begin DescriptionPanel member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end DescriptionPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin DescriptionPanel member variables
    IdentificationPanel* m_identifictionTab;
    wxSlider* m_zoomSlider;
    ImagePanel* m_stampImage;
    InventoryPanel* m_inventoryPanel;
    CharacteristicsPanel* m_characteristicsPanel;
    MiscellaneousDataPanel* m_miscellaneousTab;
    wxTextCtrl* m_description;
    wxTextCtrl* m_bkgndText;
////@end DescriptionPanel member variables
};

#endif
    // _DESCRIPTIONPANEL_H_
