/////////////////////////////////////////////////////////////////////////////
// Name:        LabeledTextBox.cpp
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Wed 30 Mar 2022 14:21:25 CDT
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Wed 30 Mar 2022 14:21:25 CDT

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "LabeledTextBox.h"

////@begin XPM images

////@end XPM images


/*
 * LabeledTextBox type definition
 */

IMPLEMENT_DYNAMIC_CLASS( LabeledTextBox, wxPanel )


/*
 * LabeledTextBox event table definition
 */

BEGIN_EVENT_TABLE( LabeledTextBox, wxPanel )

////@begin LabeledTextBox event table entries
    EVT_TEXT( ID_TEXTCTRL, LabeledTextBox::OnTextctrlTextUpdated )
////@end LabeledTextBox event table entries

END_EVENT_TABLE()


/*
 * LabeledTextBox constructors
 */

LabeledTextBox::LabeledTextBox()
{
    Init();
}

LabeledTextBox::LabeledTextBox( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, pos, size, style);
}


/*
 * LabeledTextBox creator
 */

bool LabeledTextBox::Create( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
////@begin LabeledTextBox creation
    SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    wxPanel::Create( parent, id, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end LabeledTextBox creation
    return true;
}


/*
 * LabeledTextBox destructor
 */

LabeledTextBox::~LabeledTextBox()
{
////@begin LabeledTextBox destruction
////@end LabeledTextBox destruction
}


/*
 * Member initialisation
 */

void LabeledTextBox::Init()
{
////@begin LabeledTextBox member initialisation
    m_idLabel = NULL;
    m_idText = NULL;
////@end LabeledTextBox member initialisation
}


/*
 * Control creation for LabeledTextBox
 */

void LabeledTextBox::CreateControls()
{    
////@begin LabeledTextBox content construction
    // Generated by DialogBlocks, Wed 30 Mar 2022 14:21:25 CDT (unregistered)

    LabeledTextBox* itemPanel1 = this;

    wxBoxSizer* itemBoxSizer1 = new wxBoxSizer(wxHORIZONTAL);
    itemPanel1->SetSizer(itemBoxSizer1);

    m_idLabel = new wxStaticText( itemPanel1, wxID_STATIC, _("Static text"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer1->Add(m_idLabel, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 0);

    m_idText = new wxTextCtrl( itemPanel1, ID_TEXTCTRL, wxEmptyString, wxDefaultPosition, wxSize(-1, 26), 0 );
    itemBoxSizer1->Add(m_idText, 1, wxGROW|wxLEFT|wxRIGHT, 4);

////@end LabeledTextBox content construction
}


/*
 * wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL
 */

void LabeledTextBox::OnTextctrlTextUpdated( wxCommandEvent& event )
{
////@begin wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL in LabeledTextBox.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL in LabeledTextBox. 
}


/*
 * Should we show tooltips?
 */

bool LabeledTextBox::ShowToolTips()
{
    return true;
}

/*
 * Get bitmap resources
 */

wxBitmap LabeledTextBox::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin LabeledTextBox bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end LabeledTextBox bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon LabeledTextBox::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin LabeledTextBox icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end LabeledTextBox icon retrieval
}
