/////////////////////////////////////////////////////////////////////////////
// Name:        LabeledTextBox.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Wed 30 Mar 2022 14:21:25 CDT
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Wed 30 Mar 2022 14:21:25 CDT

#ifndef _LABELEDTEXTBOX_H_
#define _LABELEDTEXTBOX_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_LABLEDTEXTBOX 10000
#define ID_TEXTCTRL 10001
#define SYMBOL_LABELEDTEXTBOX_STYLE wxTAB_TRAVERSAL
#define SYMBOL_LABELEDTEXTBOX_TITLE _("LabledTextBox")
#define SYMBOL_LABELEDTEXTBOX_IDNAME ID_LABLEDTEXTBOX
#define SYMBOL_LABELEDTEXTBOX_SIZE wxDefaultSize
#define SYMBOL_LABELEDTEXTBOX_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * LabeledTextBox class declaration
 */

class LabeledTextBox: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( LabeledTextBox )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    LabeledTextBox();
    LabeledTextBox( wxWindow* parent, wxWindowID id = SYMBOL_LABELEDTEXTBOX_IDNAME, const wxPoint& pos = SYMBOL_LABELEDTEXTBOX_POSITION, const wxSize& size = SYMBOL_LABELEDTEXTBOX_SIZE, long style = SYMBOL_LABELEDTEXTBOX_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_LABELEDTEXTBOX_IDNAME, const wxPoint& pos = SYMBOL_LABELEDTEXTBOX_POSITION, const wxSize& size = SYMBOL_LABELEDTEXTBOX_SIZE, long style = SYMBOL_LABELEDTEXTBOX_STYLE );

    /// Destructor
    ~LabeledTextBox();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin LabeledTextBox event handler declarations
    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL
    void OnTextctrlTextUpdated( wxCommandEvent& event );

////@end LabeledTextBox event handler declarations

////@begin LabeledTextBox member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end LabeledTextBox member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin LabeledTextBox member variables
    wxStaticText* m_idLabel;
    wxTextCtrl* m_idText;
////@end LabeledTextBox member variables
};

#endif
    // _LABELEDTEXTBOX_H_
