/////////////////////////////////////////////////////////////////////////////
// Name:        StampDetailsDialog.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Wed 30 Mar 2022 14:21:07 CDT
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Wed 30 Mar 2022 14:21:07 CDT

#ifndef _STAMPDETAILSDIALOG_H_
#define _STAMPDETAILSDIALOG_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/listctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class LabeledTextBox;
class wxListCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_STAMPDETAILSDIALOG 10000
#define ID_IDLABELTEXTBOX 10007
#define ID_NAMELABELEDTEXTBOX 10009
#define ID_HEIGHTLABELEDTEXTBOX 10001
#define ID_WIDTHLABELEDTEXTBOX 10002
#define ID_REFRESHBUTTON 10005
#define ID_VALIDATEBUTTON 10008
#define ID_LISTCTRL 10006
#define SYMBOL_STAMPDETAILSDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_STAMPDETAILSDIALOG_TITLE _("StampDetailsDialog")
#define SYMBOL_STAMPDETAILSDIALOG_IDNAME ID_STAMPDETAILSDIALOG
#define SYMBOL_STAMPDETAILSDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_STAMPDETAILSDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * StampDetailsDialog class declaration
 */

class StampDetailsDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( StampDetailsDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    StampDetailsDialog();
    StampDetailsDialog( wxWindow* parent, wxWindowID id = SYMBOL_STAMPDETAILSDIALOG_IDNAME, const wxString& caption = SYMBOL_STAMPDETAILSDIALOG_TITLE, const wxPoint& pos = SYMBOL_STAMPDETAILSDIALOG_POSITION, const wxSize& size = SYMBOL_STAMPDETAILSDIALOG_SIZE, long style = SYMBOL_STAMPDETAILSDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_STAMPDETAILSDIALOG_IDNAME, const wxString& caption = SYMBOL_STAMPDETAILSDIALOG_TITLE, const wxPoint& pos = SYMBOL_STAMPDETAILSDIALOG_POSITION, const wxSize& size = SYMBOL_STAMPDETAILSDIALOG_SIZE, long style = SYMBOL_STAMPDETAILSDIALOG_STYLE );

    /// Destructor
    ~StampDetailsDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin StampDetailsDialog event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_REFRESHBUTTON
    void OnRefreshButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_CANCEL
    void OnCancelClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_OK
    void OnOkClick( wxCommandEvent& event );

////@end StampDetailsDialog event handler declarations

////@begin StampDetailsDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end StampDetailsDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin StampDetailsDialog member variables
    LabeledTextBox* m_id;
    LabeledTextBox* m_name;
    LabeledTextBox* m_height;
    LabeledTextBox* m_width;
    wxButton* m_validate;
    wxListCtrl* m_statusList;
////@end StampDetailsDialog member variables
};

#endif
    // _STAMPDETAILSDIALOG_H_
