/////////////////////////////////////////////////////////////////////////////
// Name:        GalleryPanel.cpp
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Mon 21 Feb 2022 17:10:35 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Mon 21 Feb 2022 17:10:35 CST

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "GalleryPanel.h"

////@begin XPM images

////@end XPM images


/*
 * GalleryPanel type definition
 */

IMPLEMENT_DYNAMIC_CLASS( GalleryPanel, wxPanel )


/*
 * GalleryPanel event table definition
 */

BEGIN_EVENT_TABLE( GalleryPanel, wxPanel )

////@begin GalleryPanel event table entries
////@end GalleryPanel event table entries

END_EVENT_TABLE()


/*
 * GalleryPanel constructors
 */

GalleryPanel::GalleryPanel()
{
    Init();
}

GalleryPanel::GalleryPanel( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, pos, size, style);
}


/*
 * GalleryPanel creator
 */

bool GalleryPanel::Create( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
////@begin GalleryPanel creation
    SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    wxPanel::Create( parent, id, pos, size, style );

    CreateControls();
    Centre();
////@end GalleryPanel creation
    return true;
}


/*
 * GalleryPanel destructor
 */

GalleryPanel::~GalleryPanel()
{
////@begin GalleryPanel destruction
////@end GalleryPanel destruction
}


/*
 * Member initialisation
 */

void GalleryPanel::Init()
{
////@begin GalleryPanel member initialisation
    m_scrolledWindow = NULL;
    m_sizer = NULL;
////@end GalleryPanel member initialisation
}


/*
 * Control creation for GalleryPanel
 */

void GalleryPanel::CreateControls()
{    
////@begin GalleryPanel content construction
    // Generated by DialogBlocks, Mon 21 Feb 2022 17:10:35 CST (unregistered)

    GalleryPanel* itemPanel1 = this;

    wxBoxSizer* itemBoxSizer1 = new wxBoxSizer(wxVERTICAL);
    itemPanel1->SetSizer(itemBoxSizer1);

    wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer1->Add(itemBoxSizer3, 1, wxGROW|wxALL, 0);

    m_scrolledWindow = new wxScrolledWindow( itemPanel1, ID_IMAGEGALLERYSCROLLEDWINDOW, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxHSCROLL|wxVSCROLL );
    itemBoxSizer3->Add(m_scrolledWindow, 1, wxGROW|wxALL, 0);
    m_scrolledWindow->SetScrollbars(1, 1, 0, 0);
    m_sizer = new wxGridSizer(0, 5, 0, 0);
    m_scrolledWindow->SetSizer(m_sizer);

    m_scrolledWindow->FitInside();

////@end GalleryPanel content construction
}


/*
 * Should we show tooltips?
 */

bool GalleryPanel::ShowToolTips()
{
    return true;
}

/*
 * Get bitmap resources
 */

wxBitmap GalleryPanel::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin GalleryPanel bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end GalleryPanel bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon GalleryPanel::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin GalleryPanel icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end GalleryPanel icon retrieval
}
