/////////////////////////////////////////////////////////////////////////////
// Name:        ManageCatalogData.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Sat 22 Jan 2022 13:01:18 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Sat 22 Jan 2022 13:01:18 CST

#ifndef _MANAGECATALOGDATA_H_
#define _MANAGECATALOGDATA_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/treectrl.h"
////@end includes

#include "Defs.h"
#include "CatalogData.h"
/*!
 * Forward declarations
 */

////@begin forward declarations
class CatalogDataTreeCtrl;
////@end forward declarations

class Stamp;

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_MANAGECATALOGDATA 10000
#define ID_TEXTCTRL 10007
#define ID_TREECTRL 10010
#define SYMBOL_MANAGECATALOGDATA_STYLE wxTAB_TRAVERSAL
#define SYMBOL_MANAGECATALOGDATA_TITLE _("ManageCatalogData")
#define SYMBOL_MANAGECATALOGDATA_IDNAME ID_MANAGECATALOGDATA
#define SYMBOL_MANAGECATALOGDATA_SIZE wxSize(400, 300)
#define SYMBOL_MANAGECATALOGDATA_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ManageCatalogData class declaration
 */

class ManageCatalogData: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( ManageCatalogData )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ManageCatalogData();
    ManageCatalogData( wxWindow* parent, 
    wxWindowID id = SYMBOL_MANAGECATALOGDATA_IDNAME, 
    const wxPoint& pos = SYMBOL_MANAGECATALOGDATA_POSITION, 
    const wxSize& size = SYMBOL_MANAGECATALOGDATA_SIZE, 
    long style = SYMBOL_MANAGECATALOGDATA_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_MANAGECATALOGDATA_IDNAME, const wxPoint& pos = SYMBOL_MANAGECATALOGDATA_POSITION, const wxSize& size = SYMBOL_MANAGECATALOGDATA_SIZE, long style = SYMBOL_MANAGECATALOGDATA_STYLE );

    /// Destructor
    ~ManageCatalogData();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin ManageCatalogData event handler declarations

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL
    void OnTextctrlTextUpdated( wxCommandEvent& event );

////@end ManageCatalogData event handler declarations

////@begin ManageCatalogData member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ManageCatalogData member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

    void SetStamp( Stamp* stamp );
    
    void UpdateStatus( );

    void LoadCatalogTree( );

    void ClearCatalogTree( );

void LoadCatalog( wxString filename )
{
    GetCatalogData( )->LoadXML( filename );
    ClearCatalogTree( );
    LoadCatalogTree( );
}
void InitCatalogData()
{
        ClearCatalogTree( );
        CatalogData* catalogData = NewCatalogData( );
        SetCatalogData ( catalogData );
}

void LoadCatalogCSV( wxString filename )
{

    ClearCatalogTree( );
    CatalogData* catalogData = NewCatalogData( );
    SetCatalogData ( catalogData );
    catalogData->LoadCSV( filename );   

    LoadCatalogTree( );
}

    CatalogDataTreeCtrl* GetCatalogDataTree( ) { return m_listTree; };

 
 
////@begin ManageCatalogData member variables
    wxTextCtrl* m_title;
    CatalogDataTreeCtrl* m_listTree;
////@end ManageCatalogData member variables
  
    wxTreeItemId m_draggedItem;
    
    Stamp* m_stamp;
    
    wxTreeItemId m_currentItem;

};

#endif
    // _MANAGECATALOGDATA_H_
