/////////////////////////////////////////////////////////////////////////////
// Name:        SettingsPanel.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Tue 11 Jan 2022 10:57:16 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Tue 11 Jan 2022 10:57:16 CST

#ifndef _SETTINGSPANEL_H_
#define _SETTINGSPANEL_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class LabeledTextBox;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_SETTINGSPANEL 10000
#define ID_IMAGEDIRECTORTEXTBOX 11001
#define ID_WORKINGDIRECTORYTEXTBOX 11002
#define ID_COUNTRYTEXTBOX 11003
#define ID_CATALOGTEXTBOX 11004
#define ID_OPENLASTCHECKBOX 11005
#define SYMBOL_SETTINGSPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_SETTINGSPANEL_TITLE _("SettingsPanel")
#define SYMBOL_SETTINGSPANEL_IDNAME ID_SETTINGSPANEL
#define SYMBOL_SETTINGSPANEL_SIZE wxSize(400, 200)
#define SYMBOL_SETTINGSPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * SettingsPanel class declaration
 */

class SettingsPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( SettingsPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    SettingsPanel();
    SettingsPanel( wxWindow* parent, wxWindowID id = SYMBOL_SETTINGSPANEL_IDNAME, const wxPoint& pos = SYMBOL_SETTINGSPANEL_POSITION, const wxSize& size = SYMBOL_SETTINGSPANEL_SIZE, long style = SYMBOL_SETTINGSPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_SETTINGSPANEL_IDNAME, const wxPoint& pos = SYMBOL_SETTINGSPANEL_POSITION, const wxSize& size = SYMBOL_SETTINGSPANEL_SIZE, long style = SYMBOL_SETTINGSPANEL_STYLE );

    /// Destructor
    ~SettingsPanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin SettingsPanel event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_CANCEL
    void OnCancelClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_OK
    void OnOkClick( wxCommandEvent& event );

////@end SettingsPanel event handler declarations

////@begin SettingsPanel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end SettingsPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin SettingsPanel member variables
    LabeledTextBox* m_imageDirectory;
    LabeledTextBox* m_workingDirectory;
    LabeledTextBox* m_country;
    LabeledTextBox* m_catalog;
    wxCheckBox* m_loadLastFileAtStartUp;
////@end SettingsPanel member variables
};

#endif
    // _SETTINGSPANEL_H_
