/////////////////////////////////////////////////////////////////////////////
// Name:        StampManagerPanel.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Fri 25 Mar 2022 16:21:43 CDT
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Fri 25 Mar 2022 16:21:43 CDT

#ifndef _STAMPMANAGERPANEL_H_
#define _STAMPMANAGERPANEL_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/splitter.h"
#include "wx/treectrl.h"
#include "wx/notebook.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class StampTreeCtrl;
class wxNotebook;
class DescriptionPanel;
class wxFlexGridSizer;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_STAMPMANAGERPANEL 10000
#define ID_SPLITTERWINDOW 10003
#define ID_PANEL1 10004
#define ID_TREECTRL 10010
#define ID_NOTEBOOK 10001
#define ID_DESCRIPTIONPANELFOREIGN 10002
#define ID_GALLERYSCROLLEDWINDOW 10006
#define ID_PANEL 10005
#define SYMBOL_STAMPMANAGERPANEL_STYLE wxTAB_TRAVERSAL
#define SYMBOL_STAMPMANAGERPANEL_TITLE _("StampManagerPanel")
#define SYMBOL_STAMPMANAGERPANEL_IDNAME ID_STAMPMANAGERPANEL
#define SYMBOL_STAMPMANAGERPANEL_SIZE wxSize(400, 300)
#define SYMBOL_STAMPMANAGERPANEL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * StampManagerPanel class declaration
 */

class StampManagerPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( StampManagerPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    StampManagerPanel();
    StampManagerPanel( wxWindow* parent, wxWindowID id = SYMBOL_STAMPMANAGERPANEL_IDNAME, const wxPoint& pos = SYMBOL_STAMPMANAGERPANEL_POSITION, const wxSize& size = SYMBOL_STAMPMANAGERPANEL_SIZE, long style = SYMBOL_STAMPMANAGERPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_STAMPMANAGERPANEL_IDNAME, const wxPoint& pos = SYMBOL_STAMPMANAGERPANEL_POSITION, const wxSize& size = SYMBOL_STAMPMANAGERPANEL_SIZE, long style = SYMBOL_STAMPMANAGERPANEL_STYLE );

    /// Destructor
    ~StampManagerPanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin StampManagerPanel event handler declarations
    /// wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGED event handler for ID_NOTEBOOK
    void OnNotebookPageChanged( wxNotebookEvent& event );

////@end StampManagerPanel event handler declarations

////@begin StampManagerPanel member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end StampManagerPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin StampManagerPanel member variables
    StampTreeCtrl* m_listTree;
    wxNotebook* m_notebook;
    DescriptionPanel* m_descriptionPanel;
    wxScrolledWindow* m_galleryPage;
    wxFlexGridSizer* m_sizer;
////@end StampManagerPanel member variables
};

#endif
    // _STAMPMANAGERPANEL_H_
