/////////////////////////////////////////////////////////////////////////////
// Name:        StaticItem.cpp
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Fri 21 Jan 2022 11:02:57 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Fri 21 Jan 2022 11:02:57 CST

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "StaticItem.h"

////@begin XPM images
////@end XPM images


/*
 * StaticItem type definition
 */

IMPLEMENT_DYNAMIC_CLASS( StaticItem, wxPanel )


/*
 * StaticItem event table definition
 */

BEGIN_EVENT_TABLE( StaticItem, wxPanel )

////@begin StaticItem event table entries
    EVT_CONTEXT_MENU( StaticItem::OnContextMenu )
////@end StaticItem event table entries

END_EVENT_TABLE()


/*
 * StaticItem constructors
 */

StaticItem::StaticItem()
{
    Init();
}

StaticItem::StaticItem( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, pos, size, style);
}


/*
 * StaticItem creator
 */

bool StaticItem::Create( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style )
{
////@begin StaticItem creation
    SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY);
    wxPanel::Create( parent, id, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end StaticItem creation
    return true;
}


/*
 * StaticItem destructor
 */

StaticItem::~StaticItem()
{
////@begin StaticItem destruction
////@end StaticItem destruction
}


/*
 * Member initialisation
 */

void StaticItem::Init()
{
////@begin StaticItem member initialisation
    m_title = NULL;
    m_data = NULL;
////@end StaticItem member initialisation
}


/*
 * Control creation for StaticItem
 */

void StaticItem::CreateControls()
{    
////@begin StaticItem content construction
    // Generated by DialogBlocks, Fri 21 Jan 2022 11:04:44 CST (unregistered)

    StaticItem* itemPanel1 = this;

    wxBoxSizer* itemBoxSizer1 = new wxBoxSizer(wxHORIZONTAL);
    itemPanel1->SetSizer(itemBoxSizer1);

    m_title = new wxStaticText( itemPanel1, wxID_TITLESTATIC, _("Title"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer1->Add(m_title, 0, wxGROW, 5);

    wxStaticText* itemStaticText3 = new wxStaticText( itemPanel1, wxID_COLONSTATIC, _(":"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer1->Add(itemStaticText3, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT, 5);

    m_data = new wxStaticText( itemPanel1, wxID_VALSTATIC, _("val"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer1->Add(m_data, 1, wxGROW, 5);

////@end StaticItem content construction
}


/*
 * Should we show tooltips?
 */

bool StaticItem::ShowToolTips()
{
    return true;
}

/*
 * Get bitmap resources
 */

wxBitmap StaticItem::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin StaticItem bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end StaticItem bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon StaticItem::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin StaticItem icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end StaticItem icon retrieval
}


/*
 * wxEVT_CONTEXT_MENU event handler for ID_STATICITEM
 */

void StaticItem::OnContextMenu( wxContextMenuEvent& event )
{
////@begin wxEVT_CONTEXT_MENU event handler for ID_STATICITEM in StaticItem.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_CONTEXT_MENU event handler for ID_STATICITEM in StaticItem. 
}

