/////////////////////////////////////////////////////////////////////////////
// Name:        DefinePeriodsDialog.h
// Purpose:     
// Author:      Eddie Monroe
// Modified by: 
// Created:     Tue 11 Jan 2022 12:28:10 CST
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Tue 11 Jan 2022 12:28:10 CST

#ifndef _DEFINEPERIODSDIALOG_H_
#define _DEFINEPERIODSDIALOG_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DEFINEPERIODS 10000
#define ID_ANTIQUE 10002
#define ID_ANTIQUEYEAR 10003
#define ID_CLASSIC 10005
#define ID_MODERN 10008
#define ID_MODERNYEAR 10009
#define SYMBOL_DEFINEPERIODSDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_DEFINEPERIODSDIALOG_TITLE _("DefinePeriods")
#define SYMBOL_DEFINEPERIODSDIALOG_IDNAME ID_DEFINEPERIODS
#define SYMBOL_DEFINEPERIODSDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_DEFINEPERIODSDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * DefinePeriodsDialog class declaration
 */

class DefinePeriodsDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( DefinePeriodsDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    DefinePeriodsDialog();
    DefinePeriodsDialog( wxWindow* parent, wxWindowID id = SYMBOL_DEFINEPERIODSDIALOG_IDNAME, const wxString& caption = SYMBOL_DEFINEPERIODSDIALOG_TITLE, const wxPoint& pos = SYMBOL_DEFINEPERIODSDIALOG_POSITION, const wxSize& size = SYMBOL_DEFINEPERIODSDIALOG_SIZE, long style = SYMBOL_DEFINEPERIODSDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_DEFINEPERIODSDIALOG_IDNAME, const wxString& caption = SYMBOL_DEFINEPERIODSDIALOG_TITLE, const wxPoint& pos = SYMBOL_DEFINEPERIODSDIALOG_POSITION, const wxSize& size = SYMBOL_DEFINEPERIODSDIALOG_SIZE, long style = SYMBOL_DEFINEPERIODSDIALOG_STYLE );

    /// Destructor
    ~DefinePeriodsDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin DefinePeriodsDialog event handler declarations

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_ANTIQUE
    void OnAntiqueTextUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_ANTIQUEYEAR
    void OnAntiqueYearTextUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_CLASSIC
    void OnClassicTextUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_MODERN
    void OnModernTextUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_MODERNYEAR
    void OnModernYearTextUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_CANCEL
    void OnCancelClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_OK
    void OnOkClick( wxCommandEvent& event );

////@end DefinePeriodsDialog event handler declarations

////@begin DefinePeriodsDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end DefinePeriodsDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();
    bool IsDirty( ) { return m_dirty; };

////@begin DefinePeriodsDialog member variables
    wxTextCtrl* m_antiqueTextBox;
    wxTextCtrl* m_AntiqueYear;
    wxTextCtrl* m_classicTextBox;
    wxTextCtrl* m_modernTextBox;
    wxTextCtrl* m_modernYear;
////@end DefinePeriodsDialog member variables
   bool m_dirty;
};

#endif
    // _DEFINEPERIODSDIALOG_H_
